schema: workflow/2022.04
name: OP AI - Property Leads
settings:
  error_notification: true
  lambda_timeout: 750
triggers:
- id: hi_a1HjN3p
steps:
- namespace: trim_audio_if_needed
  runtime: nodejs20.x
  uses: "./trim_audio_if_needed/entry.js"
- namespace: transcribe
  runtime: nodejs20.x
  uses: "./transcribe/entry.js"
- namespace: check_transcript_length
  runtime: nodejs20.x
  uses: "./check_transcript_length/entry.js"
- namespace: send_back
  runtime: nodejs20.x
  uses: http-post-request@1.1.3
  props:
    httpRequest:
      auth:
        type: none
        username: ''
        password: ''
        token: ''
      body:
        contentType: multipart/form-data
        fields:
        - name: URL
          value: "{{steps.trigger.event.body.recordingUrl}}"
        - name: Transcript
          value: "{{steps.transcribe.transcript}}"
        - name: Phone Number
          value: "{{steps.trigger.event.body.contactPhone}}"
        - name: agent
          value: "{{steps.trigger.event.body.phoneUser}}"
        mode: fields
        type: fields
      headers:
      - name: ''
        value: ''
        disabled: true
      method: POST
      params:
      - name: ''
        value: ''
        disabled: true
      url: https://services.leadconnectorhq.com/hooks/MGJm2Xbycbbnnb409zoC/webhook-trigger/e01e666d-f282-4501-b24f-328124598467
      tab: Headers

